services:
  pushme-md:
    build: .
    container_name: pushme-md
    environment:
      - PORT=${PORT}
      - CACHE_CLEAR_INTERVAL=${PORT}
      - CACHE_MAX_AGE=${CACHE_MAX_AGE}
    volumes: 
      - ./renderCache:./renderCache